version: "3"
services:
  percona:
    image: percona/percona-server:latest
    working_dir: /app
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "automydumper"
      MYSQL_PASSWORD: "secret"
    volumes:
      - .:/app
  debian:
    image: debian:stretch
    command: sleep infinity
    working_dir: /app
    volumes:
      - .:/app
  centos:
    image: centos:7
    command: sleep infinity
    working_dir: /app
    volumes:
      - .:/app
